---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx-secret
      image: nginx:1.16
      env:
      - name: COOL_VARIABLE
        valueFrom:
          secretKeyRef:
            name: another-secret
            key: key1